spring:
  application:
    name: Movieflix
  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

movieflix:
  security:
    secret: "8c9799d6db49156ae000b7a5157311d3ac65f994255b04de8a3600de8792cce6"